- name: Create start scripts
  template:
    src: main.sh
    dest: /tmp/main.sh
    owner: java-user
    group: java-user

- name: stop main.sh
  shell: ". /etc/profile && /bin/bash {{pkgroot }}/main.sh stop"
