- name: yum install
  yum: name={{ item }} state=latest
  loop:
    - unzip

- name: create dir
  file:
    path: "{{ item }}"
    state: directory
    owner: java-user
    group: java-user
  loop:
    - "/data"
    - "/data/app"
    - "/data/log"
    - "/data/run"
