- name: register backup pkgname
  shell: echo "`date +%F-%H-%M`_{{ pkgname }}"
  register: backup_pkgname

- name: create pkgroot
  file:
    path: "{{ pkgroot }}"
    state: directory

- name: copy "{{ pkgname }}"
  copy:
    src: "{{ pkgsrc }}"
    dest: /tmp/
    mode: 0640

- name: Replace code
  shell: "cd {{ pkgroot }} && rm -rf * && tar xf /tmp/{{ pkgname }}"

- name: Chown
  shell: "chown -R java-user.java-user {{ pkgroot }}"

- name: Create backup dir
  file:
    path: "/opt/{{ project }}"
    state: directory 
    owner: java-user
    group: java-user

- name: Backup pkg
  copy:
    src: "/tmp/{{ pkgname }}"
    dest: "/opt/{{ project }}/{{ backup_pkgname.stdout }}"
    owner: java-user
    group: java-user
    remote_src: yes
