- name: register backup pkgname
  shell: echo "`date +%F-%H-%M`_{{ pkgname }}"
  register: backup_pkgname

- name: create pkgroot
  file:
    path: "{{ pkgroot }}"
    state: directory
    owner: java-user
    group: java-user

- name: copy "{{ pkgname }}"
  copy:
    src: "{{ pkgsrc }}"
    dest: "{{ pkgroot }}"
    mode: 0640
    owner: java-user
    group: java-user

- name: start rngd service
  service: name=rngd state=started enabled=yes

- name: Create start script
  template:
    src: main.sh
    dest: "{{ pkgroot }}/main.sh"
    owner: java-user
    group: java-user

- name: restart main.sh
  shell: ". /etc/profile && /bin/bash {{pkgroot }}/main.sh restart"
  become_user: java-user
  become_method: sudo

- name: Create backup dir
  file:
    path: "/opt/{{ project }}"
    state: directory
    owner: java-user
    group: java-user

- name: Backup pkg
  copy:
    src: "{{ pkgroot }}/{{ pkgname }}"
    dest: "/opt/{{ project }}/{{ backup_pkgname.stdout }}"
    owner: java-user
    group: java-user
    remote_src: yes

- name: delete old backup
  shell: "cd /opt/{{ project }} && ls -r *{{ pkgname }} | awk 'NR>10' |xargs rm -f"
